### ISSUE TITLE
[Parallax View] Portrait orientation on Nexus 7

### ISSUE THREAD

**Issue by fedemonte89** [MatthieuLJ/ViewPagerParallax#2]
Hello Matthieu,
I try to use your ViewPagerParallax class and everything is ok with Sony Xperia MiniPro (display 320 x 480 pixels).
But when I use Nexus 7 (2012) in portrait orientation parallax view is all white.

If I start my app on Nexus 7 (display 800 x 1280 pixels) in landscape orientation background is showed. The issue is verified just when I start Nexus 7 in portrait orientation or when I rotate the device from landscape to portrait.  If I came back to landscape the background remains white.

For the background I use a picture 2400 x 1596 pixels in res/raw folder.
Is there any solution?

Thanks
Federico

**Comment by MatthieuLJ** [comment]
Frederico,
I have not looked at that code or even used it for some time. My best guess
is that it ran out of memory to decode the bitmap. Can you try with a lower
resolution or at least higher compression ratio?
I don't really have any other idea.. but whatever you find, I will be
interested to know what it is and fix any bug there might be...
Thanks

**Comment by fedemonte89** [comment]
It's ok! With a small image it works. I am surprised by the different behavior between Sony Xperia Mini Pro and Nexus 7!

At the end I confirmed: the issue is just a memory trouble.

**Comment by MatthieuLJ** [comment]
Good..
It would be nice to have a better way to detect this problem though.
Matthieu
